config:
    include:
        - "share/lfv/train/default_v7_ntuple.yaml"

job:
    job_name: "emu-default"
    job_type: "train"
    save_dir: "run/lfv/emu"

input:
    channel: "emu"
    norm_array: true
    bkg_key: "all"
    sig_key: "all_norm"
    # all features
    selected_features:
        - "m_ll"
        - "ele_pt"
        - "mu_pt"
        - "pt_ll"
        - "dr_ll"
        - "met"
    validation_features:
        - "m_ll"
    reset_feature: true
    reset_feature_name: "m_ll"
    rm_negative_weight_events: true

train:
    model_name: "lfv_emu"
    model_class: "Model_Sequential_Flat"
    layers: 5
    nodes: 128
    dropout_rate: 0
    momentum: 0.5
    nesterov: true
    test_rate: .2
    val_split: .25
    learn_rate: 0.003
    learn_rate_decay: 1.e-4
    batch_size: 64
    epochs: 100
    sig_class_weight: 1.
    bkg_class_weight: 1.
    # early stop setups
    use_early_stop: true
    early_stop_paras:
        monitor: "val_loss"
        min_delta: 0
        patience: 3
        mode: "min"
        restore_best_weights: true

    verbose: 1
