# default settings, you can change values but don't delete any items
# please follow the syntax instruction here:
# https://docs.python.org/3/library/configparser.html#supported-ini-file-structure
# Warning: Use "" in string list. '' will not be recognized correctly

## keep general settings that shouldn't change with inputs' version ##

job:
    job_name: "train-job-default"
    save_dir: "/work/run/hh_bbll/default"

train:
    model_name: "hh_bbll_dnn"
    model_class: "Model_Sequential_Flat"
    layers: 5
    nodes: 256
    dropout_rate: 0
    momentum: 0.5
    nesterov: true
    test_rate: .2
    val_split: .2
    learn_rate: 0.005
    learn_rate_decay: 1.e-5
    batch_size: 32
    epochs: 200
    sig_class_weight: 1.
    bkg_class_weight: 1.
    # early stop setups
    early_stop_paras:
        monitor: "val_loss"
        min_delta: 0
        patience: 3
        mode: "min"
        restore_best_weights: true
    # in older tensorflow version may use "acc"
    train_metrics:
        - "plain_acc"
    train_metrics_weighted:
        - "accuracy"
        - "mean_squared_error"
    verbose: 1
