config:
    include:
        - "share/hh_bbll/train/default.yaml"

job:
    job_name: "sr1-default"
    job_type: "train"
    save_dir: "run/hh_bbll/sr1"

input:
    arr_path: "dihiggs/arrays"
    arr_version: "v8"
    campaign: "run2"
    region: "2tag_sr1"
    channel: "dummy_channel"
    sig_list:
        - "sig_nonres"
    bkg_list:
        - "bkg_diboson"
        - "bkg_fakes"
        - "bkg_Higgs"
        - "bkg_stop"
        - "bkg_ttbar"
        - "bkg_ttbarV"
        - "bkg_Zee"
        - "bkg_Zll"
        - "bkg_Zmm"

    norm_array: true
    sig_key: "sig_nonres"
    bkg_key: "all"
    # all features
    selected_features:
        - "lept_0_pt"
        - "lept_0_eta"
        - "lept_0_phi"
        - "lept_1_pt"
        - "lept_1_eta"
        - "lept_1_phi"
        - "bjet_0_pt"
        - "bjet_0_eta"
        - "bjet_0_phi"
        - "bjet_1_pt"
        - "bjet_1_eta"
        - "bjet_1_phi"
        - "ll_m"
        - "ll_pt"
        - "ll_deltar"
        - "ll_deltaeta"
        - "ll_deltaphi"
        - "bb_m"
        - "bb_pt"
        - "bb_deltapt"
        - "bb_deltar"
        - "bb_deltaeta"
        - "bb_deltaphi"
        - "deltar_min_bl"
        - "deltar_max_bl"
        - "deltar_diff_bl"
        - "met_sumet"
        - "met_met"
        - "met_phi"
        - "met_sig"
        - "mmc_mlnu3p"
        - "mt_lep0_met"
        - "mt_lep1_met"
        - "met_phi_centrality"
        - "mcoll"
        - "dphi_met_ll"
        - "sum_met_ptll"
        - "ht2"
        - "ht2r"
        - "pt_bbll_scalar"
        - "pt_bbllmet_scalar"
        - "m_bbll"
        - "m_bbllmet"
        - "m_t2_bb"
        - "m_ttbar"
        - "m_hh"
        - "is_sf"
        - "weight"
    validation_features: []
    reset_feature: false
    rm_negative_weight_events: true

train:
    model_name: "hh_bbll_dnn"
    model_class: "Model_Sequential_Flat"
    layers: 5
    nodes: 512
    dropout_rate: 0.1
    momentum: 0.5
    nesterov: true
    test_rate: .2
    val_split: .25
    learn_rate: 0.01
    learn_rate_decay: 0
    batch_size: 128
    epochs: 10
    sig_class_weight: 1.
    bkg_class_weight: 1.
    # multi-output nodes
    output_bkg_node_names:
        - "bkg_stop + bkg_ttbar + bkg_ttbarV"
        - "bkg_Zee + bkg_Zmm + bkg_Zll"
        - "bkg_fakes"
        - "bkg_diboson + bkg_Higgs"
    # early stop setups
    use_early_stop: true
    early_stop_paras:
        monitor: "val_loss"
        min_delta: 0
        patience: 3
        mode: "min"
        restore_best_weights: true
    # save model or not
    save_model: true

    verbose: 1